@HostAddress = http://localhost:5020

###
POST {{HostAddress}}/users/
Accept: application/json
Content-Type: application/json

{
  "name": "Carlos Roberto",
  "email": "carlos@teste.com"
}

###
GET {{HostAddress}}/users/
Accept: application/json

###
GET {{HostAddress}}/users/{{UserId}}
Accept: application/json

###
DELETE {{HostAddress}}/users/{{UserId}}
Accept: application/json
