@HostAddress = http://localhost:5020

###
POST {{HostAddress}}/users/
Accept: application/json
Content-Type: application/json

{
  "name": "Carlos Roberto",
  "email": "carlos@teste.com"
}

###
GET {{HostAddress}}/users/
Accept: application/json

###
GET {{HostAddress}}/users/{{QueryUserId}}
Accept: application/json

###
DELETE {{HostAddress}}/users/{{QueryUserId}}
Accept: application/json



###
POST {{HostAddress}}/company/
Accept: application/json
Content-Type: application/json

{
  "name": "Carlinhos Tech Solutions LTDA",
  "address": {
    "street": "Rua da Saudade",
    "number": 123
  }
}

###
GET {{HostAddress}}/company/
Accept: application/json

###
GET {{HostAddress}}/company/{{QueryCompanyId}}
Accept: application/json

###
DELETE {{HostAddress}}/company/{{QueryCompanyId}}
Accept: application/json



###
POST {{HostAddress}}/points/
Accept: application/json
Content-Type: application/json

{
  "hour": "2024-10-13T02:41:04Z",
  "companyId": "{{CompanyId}}",
  "userId": "{{UserId}}"
}

###
GET {{HostAddress}}/company/
Accept: application/json

###
GET {{HostAddress}}/company/{{CompanyId}}
Accept: application/json

###
DELETE {{HostAddress}}/company/{{CompanyId}}
Accept: application/json